services:
  fastdocs-db:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_DATABASE=fastdocs
      - POSTGRESQL_PASSWORD=admin
      - POSTGRESQL_USERNAME=admin
    ports:
      - "5432:5432"
    volumes:
      - fastdocs-db-data:/bitnami/postgresql
volumes:
  fastdocs-db-data:
    driver: local