services:
  fastdocs-db:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_DATABASE=fastdocs
      - POSTGRESQL_PASSWORD=mAAmW5zwzsuTa2K
      - POSTGRESQL_USERNAME=fastdocs_admin
    ports:
      - "5432:5432"
    volumes:
      - fastdocs-db-data:/bitnami/postgresql
volumes:
  fastdocs-db-data:
    driver: local